base_rotate_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: lynxmotion_base_rotate_joint
  pid: &base_rotate_position_gains
    p: 7.0
    d: 0.25
    i: 0.0
    i_clamp: 1.0
shoulder_rotate_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: lynxmotion_shoulder_rotate_joint
  pid: &shoulder_rotate_position_gains
    p: 40.0
    d: 0.5
    i: 0.0
    i_clamp: 1.0
elbow_rotate_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: lynxmotion_elbow_rotate_joint
  pid: &elbow_rotate_position_gains
    p: 20.0
    d: 0.25
    i: 0.0
    i_clamp: 1.0
wrist_rotate_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: lynxmotion_wrist_rotate_joint
  pid: &wrist_rotate_position_gains
    p: 5.0
    d: 0.25
    i: 0.0
    i_clamp: 1.0
gripper_rotate_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: lynxmotion_gripper_rotate_joint
  pid: &gripper_rotate_position_gains
    p: 2.5
    d: 0.25
    i: 0.0
    i_clamp: 1.0