## This file should be loaded under <robot description>_collision

default_collision_operations:
  - object1: lynxmotion_arm
    object2: lynxmotion_end_effector
    operation: enable

  - object1: lynxmotion_base_block
    object2: lynxmotion_base_rotate_link
    operation: disable

  - object1: lynxmotion_base_rotate_link
    object2: lynxmotion_upper_arm_link
    operation: disable

  - object1: lynxmotion_upper_arm_link
    object2: lynxmotion_fore_arm_link
    operation: disable

  - object1: lynxmotion_fore_arm_link
    object2: lynxmotion_wrist_link
    operation: disable

 