<?xml version="1.0"?>
<robot name="gaffa"
    xmlns:xi="http://www.w3.org/2001/XInclude"
    xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
    xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
    xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
    xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
    xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
    xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics"
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <include filename="$(find gaffa_description)/urdf/lynxmotion.urdf.xacro" />
    <include filename="$(find gaffa_description)/urdf/maplin.urdf.xacro" />

    <property name="GAFFA_BASE_MASS" value="100" />
    <property name="GAFFA_BASE_LENGTH" value="1" />
    <property name="GAFFA_BASE_WIDTH" value="1" />
    <property name="GAFFA_BASE_HEIGHT" value="0.018" />

    <!-- Base Block -->
    <link name="gaffa_base_block">
        <inertial>
        <mass value="${GAFFA_BASE_MASS}" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="${GAFFA_BASE_MASS*(GAFFA_BASE_WIDTH*GAFFA_BASE_WIDTH + GAFFA_BASE_HEIGHT*GAFFA_BASE_HEIGHT)/12.0}"  
                ixy="0" ixz="0" 
                iyy="${GAFFA_BASE_MASS*(GAFFA_BASE_LENGTH*GAFFA_BASE_LENGTH + GAFFA_BASE_HEIGHT*GAFFA_BASE_HEIGHT)/12.0}" 
                iyz="0" 
                izz="${GAFFA_BASE_MASS*(GAFFA_BASE_LENGTH*GAFFA_BASE_LENGTH + GAFFA_BASE_WIDTH*GAFFA_BASE_WIDTH)/12.0}" />
        </inertial> 
        <visual>
        <origin xyz="0 0 ${GAFFA_BASE_HEIGHT/2}" rpy="0 0 0" />
        <geometry name="base_block_visual_geom">
            <box size="${GAFFA_BASE_LENGTH} ${GAFFA_BASE_WIDTH} ${GAFFA_BASE_HEIGHT}" />
        </geometry>
        </visual> 
        <collision>
        <origin xyz="0 0 ${GAFFA_BASE_HEIGHT/2}" rpy="0.0 0.0 0.0" />
        <geometry name="base_block_collision_geom">
            <box size="${GAFFA_BASE_LENGTH} ${GAFFA_BASE_WIDTH} ${GAFFA_BASE_HEIGHT}" />
        </geometry>
        </collision>
    </link>
    <gazebo reference="gaffa_base_block">
        <material>Gazebo/WoodFloor</material>
        <turnGravityOff>false</turnGravityOff>
        <selfCollide>true</selfCollide>
    </gazebo>

    <xacro:maplin_arm name="maplin" parent="gaffa_base_block">
        <origin xyz="0 0 ${GAFFA_BASE_HEIGHT}" rpy="0 0 0" />
    </xacro:maplin_arm>

    <xacro:lynxmotion_arm name="lynxmotion" parent="gaffa_base_block">
        <origin xyz="0.4 -0.22 ${GAFFA_BASE_HEIGHT}" rpy="0 0 ${70.0*M_PI/180.0}" />
    </xacro:lynxmotion_arm>

    

    <gazebo>

        <!-- PR2_ACTARRAY -->
        <controller:gazebo_ros_controller_manager name="gazebo_ros_controller_manager" plugin="libgazebo_ros_controller_manager.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>1000.0</updateRate>
            <interface:audio name="gazebo_ros_controller_manager_dummy_iface" />
        </controller:gazebo_ros_controller_manager>

        <controller:gazebo_ros_time name="gazebo_ros_time" plugin="libgazebo_ros_time.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>1000.0</updateRate>
            <interface:audio name="dummy_gazebo_ros_time_iface_should_not_be_here"/>
        </controller:gazebo_ros_time>
    </gazebo>

</robot>





