<?xml version="1.0"?>
<robot
    xmlns:xi="http://www.w3.org/2001/XInclude"
    xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
    xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
    xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
    xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
    xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
    xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics"
    xmlns:xacro="http://www.ros.org/wiki/xacro">

<property name="M_PI" value="3.1415926535897931" />
<property name="BASE_MASS" value="100" />
<property name="BASE_LENGTH" value="0.3" />
<property name="BASE_WIDTH" value="0.15" />
<property name="BASE_HEIGHT" value="0.018" />

<property name="BASE_ROTATE_MASS" value="0.25" />
<property name="BASE_ROTATE_RADIUS" value="0.05" />
<property name="BASE_ROTATE_HEIGHT" value="0.0466" />

<property name="SHOULDER_HEIGHT" value="0.06193" />

<property name="UPPER_ARM_MASS" value="0.1" />
<property name="UPPER_ARM_LENGTH" value="0.154" />
<property name="UPPER_ARM_WIDTH" value="0.052" />
<property name="UPPER_ARM_HEIGHT" value="0.0244" />

<!-- Mass includes both elbow and wrist servos -->
<property name="FORE_ARM_MASS" value="0.21" />
<property name="FORE_ARM_LENGTH" value="0.154" />
<property name="FORE_ARM_WIDTH" value="0.053" />
<property name="FORE_ARM_HEIGHT" value="0.0244" />

<!-- Mass includes gripper rotate servo -->
<property name="WRIST_MASS" value="0.065" /> 
<property name="WRIST_LENGTH" value="0.0346" />
<property name="WRIST_WIDTH" value="0.052" />
<property name="WRIST_HEIGHT" value="0.0244" />

<!-- Mass includes gripper 'grip' servo -->
<property name="GRIPPER_BASE_MASS" value="0.065" /> 
<property name="GRIPPER_BASE_LENGTH" value="0.037" />
<property name="GRIPPER_BASE_WIDTH" value="0.0648" />
<property name="GRIPPER_BASE_HEIGHT" value="0.0244" />

<property name="GRIPPER_FINGER_MASS" value="0.01" /> 
<property name="GRIPPER_FINGER_LENGTH" value="0.0315" />
<property name="GRIPPER_FINGER_WIDTH" value="0.0144" />
<property name="GRIPPER_FINGER_HEIGHT" value="0.0244" />

<xacro:macro name="lynxmotion_arm" params="parent name *origin">

<!-- Base Block -->
<joint name="${name}_base_block_joint" type="fixed" >
    <axis xyz="1 0 0" />
    <limit upper="0" lower="0" effort="100" velocity="5" />
    <parent link="${parent}" />
    <xacro:insert_block name="origin" />
    <child link="${name}_base_block" />
</joint>
<link name="${name}_base_block">
    <inertial>
    <mass value="${BASE_MASS}" />
    <origin xyz="0 0 0" rpy="0 0 0" />
    <inertia ixx="${BASE_MASS*(BASE_WIDTH*BASE_WIDTH + BASE_HEIGHT*BASE_HEIGHT)/12.0}"  
            ixy="0" ixz="0" 
            iyy="${BASE_MASS*(BASE_LENGTH*BASE_LENGTH + BASE_HEIGHT*BASE_HEIGHT)/12.0}" 
            iyz="0" 
            izz="${BASE_MASS*(BASE_LENGTH*BASE_LENGTH + BASE_WIDTH*BASE_WIDTH)/12.0}" />
    </inertial> 
    <visual>
    <origin xyz="0 0 ${BASE_HEIGHT/2}" rpy="0 0 0" />
    <geometry name="base_block_visual_geom">
        <box size="${BASE_LENGTH} ${BASE_WIDTH} ${BASE_HEIGHT}" />
    </geometry>
    </visual> 
    <collision>
    <origin xyz="0 0 ${BASE_HEIGHT/2}" rpy="0.0 0.0 0.0" />
    <geometry name="base_block_collision_geom">
        <box size="${BASE_LENGTH} ${BASE_WIDTH} ${BASE_HEIGHT}" />
    </geometry>
    </collision>
</link>
<gazebo reference="${name}_base_block">
    <material>Gazebo/LightWood</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
</gazebo>

<!-- Base Rotate -->
<joint name="${name}_base_rotate_joint" type="revolute" >
    <axis xyz="0 0 1" />
    <limit upper="${M_PI/2}" lower="${-M_PI/2}" effort="100" velocity="5" />
    <parent link="${name}_base_block" />
    <origin xyz="0 0 ${BASE_ROTATE_HEIGHT/2 + BASE_HEIGHT}" rpy="0 0 0" />
    <child link="${name}_base_rotate_link" />
</joint>
<link name="${name}_base_rotate_link">
    <inertial >
    <mass value="${BASE_ROTATE_MASS}" />
    <origin xyz="0 0 0" /> 
    <inertia ixx="${BASE_ROTATE_MASS*(3*BASE_ROTATE_RADIUS*BASE_ROTATE_RADIUS + BASE_ROTATE_HEIGHT*BASE_ROTATE_HEIGHT)/12.0}" 
            ixy="0.0"  ixz="0.0"  
            iyy="${BASE_ROTATE_MASS*(3*BASE_ROTATE_RADIUS*BASE_ROTATE_RADIUS + BASE_ROTATE_HEIGHT*BASE_ROTATE_HEIGHT)/12.0}"  
            iyz="0.0"  
            izz="${(BASE_ROTATE_MASS*BASE_ROTATE_RADIUS*BASE_ROTATE_RADIUS)/2.0}" />
    </inertial>
    <visual >
    <origin xyz="0.0 0 0" rpy="0 0 0" />
    <geometry name="base_rotate_visual_geom">
        <cylinder radius="${BASE_ROTATE_RADIUS}" length="${BASE_ROTATE_HEIGHT}" />
    </geometry>
    </visual>
    <collision >
    <origin xyz="0.0 0 0" rpy="0 0 0" />
    <geometry name="base_rotate_collision_geom">
        <cylinder radius="${BASE_ROTATE_RADIUS}" length="${BASE_ROTATE_HEIGHT}" />
    </geometry>
    </collision>
</link>
<gazebo reference="${name}_base_rotate_link">
    <material>Gazebo/Red</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
</gazebo>

<!-- Shoulder and Upper arm -->
<joint name="${name}_shoulder_rotate_joint" type="revolute" >
    <axis xyz="0 0 1" />
    <limit upper="${3*M_PI/4}" lower="0" effort="100" velocity="5" />
    <parent link="${name}_base_rotate_link" />
    <origin xyz="0 0 ${SHOULDER_HEIGHT - BASE_ROTATE_HEIGHT/2}" rpy="${M_PI/2} 0 0" />
    <child link="${name}_upper_arm_link" />
</joint>
<link name="${name}_upper_arm_link">
    <inertial >
    <mass value="${UPPER_ARM_MASS}" />
    <origin xyz="${UPPER_ARM_LENGTH/2} 0 0" /> 
    <inertia ixx="${UPPER_ARM_MASS*(UPPER_ARM_WIDTH*UPPER_ARM_WIDTH + UPPER_ARM_HEIGHT*UPPER_ARM_HEIGHT)/12.0}"  
            ixy="0" ixz="0" 
            iyy="${UPPER_ARM_MASS*(UPPER_ARM_LENGTH*UPPER_ARM_LENGTH + UPPER_ARM_WIDTH*UPPER_ARM_WIDTH)/12.0}" 
            iyz="0" 
            izz="${UPPER_ARM_MASS*(UPPER_ARM_LENGTH*UPPER_ARM_LENGTH + UPPER_ARM_HEIGHT*UPPER_ARM_HEIGHT)/12.0}" />
    </inertial>
    <visual >
    <origin xyz="${UPPER_ARM_LENGTH/2} 0 0.0" rpy="0 0 0" />
    <geometry name="upper_arm_visual_geom">
        <box size="${UPPER_ARM_LENGTH} ${UPPER_ARM_HEIGHT} ${UPPER_ARM_WIDTH}" />
    </geometry>
    </visual>
    <collision >
    <origin xyz="${UPPER_ARM_LENGTH/2} 0 0.0" rpy="0 0 0" />
    <geometry name="upper_arm_collision_geom">
        <box size="${UPPER_ARM_LENGTH} ${UPPER_ARM_HEIGHT} ${UPPER_ARM_WIDTH}" />
    </geometry>
    </collision>
</link>
<gazebo reference="${name}_upper_arm_link">
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
</gazebo>

<!-- Elbow and Forearm -->
<joint name="${name}_elbow_rotate_joint" type="revolute" >
    <axis xyz="0 0 1" />
    <limit upper="0" lower="${-3*M_PI/4}" effort="100" velocity="5" />
    <parent link="${name}_upper_arm_link" />
    <origin xyz="${UPPER_ARM_LENGTH} 0 0.0" rpy="0 0 0" />
    <child link="${name}_fore_arm_link" />
</joint>
<link name="${name}_fore_arm_link">
    <inertial >
    <mass value="${FORE_ARM_MASS}" />
    <origin xyz="${FORE_ARM_LENGTH/2} 0 0" /> 
    <inertia ixx="${FORE_ARM_MASS*(FORE_ARM_WIDTH*FORE_ARM_WIDTH + FORE_ARM_HEIGHT*FORE_ARM_HEIGHT)/12.0}"  
            ixy="0" ixz="0" 
            iyy="${FORE_ARM_MASS*(FORE_ARM_LENGTH*FORE_ARM_LENGTH + FORE_ARM_WIDTH*FORE_ARM_WIDTH)/12.0}" 
            iyz="0" 
            izz="${FORE_ARM_MASS*(FORE_ARM_LENGTH*FORE_ARM_LENGTH + FORE_ARM_HEIGHT*FORE_ARM_HEIGHT)/12.0}" />
    </inertial>
    <visual >
    <origin xyz="${FORE_ARM_LENGTH/2} 0 0.0" rpy="0 0 0" />
    <geometry name="fore_arm_visual_geom">
        <box size="${FORE_ARM_LENGTH} ${FORE_ARM_HEIGHT} ${FORE_ARM_WIDTH}" />
    </geometry>
    </visual>
    <collision >
    <origin xyz="${FORE_ARM_LENGTH/2} 0 0.0" rpy="0 0 0" />
    <geometry name="fore_arm_collision_geom">
        <box size="${FORE_ARM_LENGTH} ${FORE_ARM_HEIGHT} ${FORE_ARM_WIDTH}" />
    </geometry>
    </collision>
</link>
<gazebo reference="${name}_fore_arm_link">
    <material>Gazebo/White</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
</gazebo>

<!-- Wrist -->
<joint name="${name}_wrist_rotate_joint" type="revolute" >
    <axis xyz="0 0 1" />
    <limit upper="${M_PI}" lower="${0}" effort="100" velocity="5" />
    <parent link="${name}_fore_arm_link" />
    <origin xyz="${FORE_ARM_LENGTH} 0 0.0" rpy="0 0 ${-M_PI/2}" />
    <child link="${name}_wrist_link" />
</joint>
<link name="${name}_wrist_link">
    <inertial >
    <mass value="${WRIST_MASS}" />
    <origin xyz="${WRIST_LENGTH/2} 0 0" /> 
    <inertia ixx="${WRIST_MASS*(WRIST_WIDTH*WRIST_WIDTH + WRIST_HEIGHT*WRIST_HEIGHT)/12.0}"  
            ixy="0" ixz="0" 
            iyy="${WRIST_MASS*(WRIST_LENGTH*WRIST_LENGTH + WRIST_WIDTH*WRIST_WIDTH)/12.0}" 
            iyz="0" 
            izz="${WRIST_MASS*(WRIST_LENGTH*WRIST_LENGTH + WRIST_HEIGHT*WRIST_HEIGHT)/12.0}" />
    </inertial>
    <visual >
    <origin xyz="${WRIST_LENGTH/2} 0 0.0" rpy="0 0 0" />
    <geometry name="wrist_visual_geom">
        <box size="${WRIST_LENGTH} ${WRIST_HEIGHT} ${WRIST_WIDTH}" />
    </geometry>
    </visual>
    <collision >
    <origin xyz="${WRIST_LENGTH/2} 0 0.0" rpy="0 0 0" />
    <geometry name="wrist_collision_geom">
        <box size="${WRIST_LENGTH} ${WRIST_HEIGHT} ${WRIST_WIDTH}" />
    </geometry>
    </collision>
</link>
<gazebo reference="${name}_wrist_link">
    <material>Gazebo/Red</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
</gazebo>

<!-- Gripper base -->
<joint name="${name}_gripper_rotate_joint" type="revolute" >
    <axis xyz="0 0 1" />
    <limit upper="${M_PI/2}" lower="${-M_PI/2}" effort="100" velocity="5" />
    <parent link="${name}_wrist_link" />
    <origin xyz="${WRIST_LENGTH} 0 0.0" rpy="0 ${M_PI/2} 0" />
    <child link="${name}_gripper_base_link" />
</joint>
<link name="${name}_gripper_base_link">
    <inertial >
    <mass value="${GRIPPER_BASE_MASS}" />
    <origin xyz="${GRIPPER_BASE_LENGTH/2} 0 0" /> 
    <inertia ixx="${GRIPPER_BASE_MASS*(GRIPPER_BASE_LENGTH*GRIPPER_BASE_LENGTH + GRIPPER_BASE_HEIGHT*GRIPPER_BASE_HEIGHT)/12.0}" 
            ixy="0" ixz="0" 
            iyy="${GRIPPER_BASE_MASS*(GRIPPER_BASE_LENGTH*GRIPPER_BASE_LENGTH + GRIPPER_BASE_WIDTH*GRIPPER_BASE_WIDTH)/12.0}"
            iyz="0" 
            izz="${GRIPPER_BASE_MASS*(GRIPPER_BASE_WIDTH*GRIPPER_BASE_WIDTH + GRIPPER_BASE_HEIGHT*GRIPPER_BASE_HEIGHT)/12.0}" />
    </inertial>
    <visual >
    <origin xyz="0 0 ${GRIPPER_BASE_LENGTH/2}" rpy="0 0 0" />
    <geometry name="gripper_base_visual_geom">
        <box size="${GRIPPER_BASE_WIDTH} ${GRIPPER_BASE_HEIGHT} ${GRIPPER_BASE_LENGTH}" />
    </geometry>
    </visual>
    <collision >
    <origin xyz="0 0 ${GRIPPER_BASE_LENGTH/2}" rpy="0 0 0" />
    <geometry name="gripper_base_collision_geom">
        <box size="${GRIPPER_BASE_WIDTH} ${GRIPPER_BASE_HEIGHT} ${GRIPPER_BASE_LENGTH}" />
    </geometry>
    </collision>
</link>
<gazebo reference="${name}_gripper_base_link">
    <material>Gazebo/BumpyMetal</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
</gazebo>

<!-- Gripper left finger -->
<joint name="${name}_gripper_left_prismatic_joint" type="prismatic" >
    <axis xyz="1 0 0" />
    <!--<limit upper="${GRIPPER_BASE_WIDTH/2 - GRIPPER_FINGER_WIDTH/2}" lower="${GRIPPER_FINGER_WIDTH/2}" effort="100" velocity="5" />-->
    <limit upper="${GRIPPER_BASE_WIDTH/2 - GRIPPER_FINGER_WIDTH/2}" lower="${GRIPPER_BASE_WIDTH/2 - GRIPPER_FINGER_WIDTH/2}" effort="100" velocity="5" />
    <parent link="${name}_gripper_base_link" />
    <origin xyz="0 0 ${GRIPPER_BASE_LENGTH}" rpy="0 0 0" />
    <child link="${name}_gripper_left_finger_link" />
</joint>
<link name="${name}_gripper_left_finger_link">
    <inertial >
    <mass value="${GRIPPER_FINGER_MASS}" />
    <origin xyz="${GRIPPER_FINGER_LENGTH/2} 0 0" /> 
    <inertia ixx="${GRIPPER_FINGER_MASS*(GRIPPER_FINGER_LENGTH*GRIPPER_FINGER_LENGTH + GRIPPER_FINGER_HEIGHT*GRIPPER_FINGER_HEIGHT)/12.0}" 
            ixy="0" ixz="0" 
            iyy="${GRIPPER_FINGER_MASS*(GRIPPER_FINGER_LENGTH*GRIPPER_FINGER_LENGTH + GRIPPER_FINGER_WIDTH*GRIPPER_FINGER_WIDTH)/12.0}"
            iyz="0" 
            izz="${GRIPPER_FINGER_MASS*(GRIPPER_FINGER_WIDTH*GRIPPER_FINGER_WIDTH + GRIPPER_FINGER_HEIGHT*GRIPPER_FINGER_HEIGHT)/12.0}" />
    </inertial>
    <visual >
    <origin xyz="0 0 ${GRIPPER_FINGER_LENGTH/2}" rpy="0 0 0" />
    <geometry name="gripper_finger_visual_geom">
        <box size="${GRIPPER_FINGER_WIDTH} ${GRIPPER_FINGER_HEIGHT} ${GRIPPER_FINGER_LENGTH}" />
    </geometry>
    </visual>
    <collision >
    <origin xyz="0 0 ${GRIPPER_FINGER_LENGTH/2}" rpy="0 0 0" />
    <geometry name="gripper_finger_collision_geom">
        <box size="${GRIPPER_FINGER_WIDTH} ${GRIPPER_FINGER_HEIGHT} ${GRIPPER_FINGER_LENGTH}" />
    </geometry>
    </collision>
</link>
<gazebo reference="${name}_gripper_left_finger_link">
    <material>Gazebo/BumpyMetal</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
</gazebo>

<!-- Gripper right finger -->
<joint name="${name}_gripper_right_prismatic_joint" type="prismatic" >
    <axis xyz="1 0 0" />
    <!--<limit upper="${GRIPPER_BASE_WIDTH/2 - GRIPPER_FINGER_WIDTH/2}" lower="${GRIPPER_FINGER_WIDTH/2}" effort="100" velocity="5" />-->
    <limit upper="${GRIPPER_BASE_WIDTH/2 - GRIPPER_FINGER_WIDTH/2}" lower="${GRIPPER_BASE_WIDTH/2 - GRIPPER_FINGER_WIDTH/2}" effort="100" velocity="5" />
    <parent link="${name}_gripper_base_link" />
    <origin xyz="0 0 ${GRIPPER_BASE_LENGTH}" rpy="0 0 ${M_PI}" />
    <child link="${name}_gripper_right_finger_link" />
</joint>
<link name="${name}_gripper_right_finger_link">
    <inertial >
    <mass value="${GRIPPER_FINGER_MASS}" />
    <origin xyz="${GRIPPER_FINGER_LENGTH/2} 0 0" /> 
    <inertia ixx="${GRIPPER_FINGER_MASS*(GRIPPER_FINGER_LENGTH*GRIPPER_FINGER_LENGTH + GRIPPER_FINGER_HEIGHT*GRIPPER_FINGER_HEIGHT)/12.0}" 
            ixy="0" ixz="0" 
            iyy="${GRIPPER_FINGER_MASS*(GRIPPER_FINGER_LENGTH*GRIPPER_FINGER_LENGTH + GRIPPER_FINGER_WIDTH*GRIPPER_FINGER_WIDTH)/12.0}"
            iyz="0" 
            izz="${GRIPPER_FINGER_MASS*(GRIPPER_FINGER_WIDTH*GRIPPER_FINGER_WIDTH + GRIPPER_FINGER_HEIGHT*GRIPPER_FINGER_HEIGHT)/12.0}" />
    </inertial>
    <visual >
    <origin xyz="0 0 ${GRIPPER_FINGER_LENGTH/2}" rpy="0 0 0" />
    <geometry name="gripper_finger_visual_geom">
        <box size="${GRIPPER_FINGER_WIDTH} ${GRIPPER_FINGER_HEIGHT} ${GRIPPER_FINGER_LENGTH}" />
    </geometry>
    </visual>
    <collision >
    <origin xyz="0 0 ${GRIPPER_FINGER_LENGTH/2}" rpy="0 0 0" />
    <geometry name="gripper_finger_collision_geom">
        <box size="${GRIPPER_FINGER_WIDTH} ${GRIPPER_FINGER_HEIGHT} ${GRIPPER_FINGER_LENGTH}" />
    </geometry>
    </collision>
</link>
<gazebo reference="${name}_gripper_right_finger_link">
    <material>Gazebo/BumpyMetal</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
</gazebo>

<!-- mechanism controls -->
<transmission type="pr2_mechanism_model/SimpleTransmission" name="base_rotate_trans">
    <actuator name="base_rotate_motor" />
    <joint name="${name}_base_rotate_joint" />
    <mechanicalReduction>1</mechanicalReduction>
    <motorTorqueConstant>1</motorTorqueConstant>
</transmission>
<transmission type="pr2_mechanism_model/SimpleTransmission" name="shoulder_rotate_trans">
    <actuator name="shoulder_rotate_motor" />
    <joint name="${name}_shoulder_rotate_joint" />
    <mechanicalReduction>1</mechanicalReduction>
    <motorTorqueConstant>1</motorTorqueConstant>
</transmission>
<transmission type="pr2_mechanism_model/SimpleTransmission" name="elbow_rotate_trans">
    <actuator name="elbow_rotate_motor" />
    <joint name="${name}_elbow_rotate_joint" />
    <mechanicalReduction>1</mechanicalReduction>
    <motorTorqueConstant>1</motorTorqueConstant>
</transmission>
<transmission type="pr2_mechanism_model/SimpleTransmission" name="wrist_rotate_trans">
    <actuator name="wrist_rotate_motor" />
    <joint name="${name}_wrist_rotate_joint" />
    <mechanicalReduction>1</mechanicalReduction>
    <motorTorqueConstant>1</motorTorqueConstant>
</transmission>
<transmission type="pr2_mechanism_model/SimpleTransmission" name="gripper_rotate_trans">
    <actuator name="gripper_rotate_motor" />
    <joint name="${name}_gripper_rotate_joint" />
    <mechanicalReduction>1</mechanicalReduction>
    <motorTorqueConstant>1</motorTorqueConstant>
</transmission>
</xacro:macro>

</robot>





